name: First_Workflow

on: push

jobs:
  
  First_Job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "First Step"
        run: |
           echo "My First Step"
        shell: bash
